# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  repository_dispatch:
    types: github_deploy
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run SSH command
      # You may pin to the exact commit or the version.
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
            # Command to execute on the remote server.
            command: cd ~/bots/repos/Norm && git reset --hard && git pull && (exec ./deploy '${{ secrets.PASSWORD }}' &> /dev/null &);
            # Hostname or IP address of the server.
            host: ${{ secrets.HOST }}
            # Username for authentication.
            username: ${{ secrets.USERNAME }}
            # Port number of the server.
            port: ${{ secrets.PORT }}
            # Password for password-based user authentication.
            password: ${{ secrets.PASSWORD }}
